name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: The action fails when...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure the action with...
        2. Push a tag...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The action should generate release notes...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The action failed with error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Action Configuration
      description: Your workflow configuration (sanitize any sensitive information)
      render: yaml
      placeholder: |
        - uses: tako-dayo8/auto-release-notes@v1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            template: standard
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Action Version
      description: Which version of the action are you using?
      placeholder: v1.0.0 or @v1
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output from the workflow run
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
