name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which documentation needs improvement?
      options:
        - README
        - README_JP (Japanese)
        - CONTRIBUTING
        - Code comments
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation that needs improvement?
      placeholder: README.md, line 45 or examples/basic-usage.yml
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: What's wrong or missing in the current documentation?
      placeholder: The explanation of the template parameter is unclear...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: It should explain that...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'd like to submit a PR to fix this

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the documentation issue
