# No GitHub Release Example
# Only updates CHANGELOG.md without creating a GitHub Release

name: Update Changelog Only

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Changelog
        uses: your-username/auto-release-notes@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-github-release: false  # Only update files, no GitHub Release
          version-file: false  # Only update main CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md for ${{ github.ref_name }}"
          git push origin HEAD:main
