# Exclusions Example
# Demonstrates filtering PRs and commits from release notes

name: Release with Custom Exclusions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        uses: tako-dayo8/auto-release-notes@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Exclude PRs with these labels from the changelog
          # Default: skip-changelog,no-changelog
          exclude-labels: skip-changelog,internal,wip,dependencies

      # Note: Chore commits (chore:) are excluded by default
      # Bot contributions (dependabot, renovate, etc.) are also excluded automatically
